[package]
name = "rust-graphql-backend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4"
actix-web-lab = "0.16.1"
actix-cors = "0.6.1"
juniper = "0.15.9"

env_logger = "0.9.0"
log = "0.4.17"
